version: "3.9"

services:

  backend:
    build: ./Server
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=homecare_db;Username=postgres;Password=123
      #ConnectionStrings__Default=Host=postgres;Port=5433;Database=myappdb;Username=postgres;Password=password
      - Jwt__Key=s9HOEh+1Prj4kpwFxXi7lp2ImMAM343YDNWTEZaW0MM=
      - Jwt__Issuer=FS1
      - Jwt__Audience=FS1

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: homecare_db
    ports:
      - "5433:5432"
    volumes:
      - hc_postgres_data:/var/lib/postgresql/data
      - ./postgres_db/hc_db.sql:/docker-entrypoint-initdb.d/backup.sql


volumes:
  hc_postgres_data:


# services:
#   backend:
#     build: .
#     depends_on:
#       - postgres
#     environment:
#       - ConnectionStrings__Default=Host=postgres;Port=5432;Database=myappdb;Username=postgres;Password=password

#   frontend:
#     build: .

#   postgres:
#     image: postgres:17
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: myappdb
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: