--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2026-05-30 09:14:17 AEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 16893)
-- Name: auth; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA auth;


ALTER SCHEMA auth OWNER TO postgres;

--
-- TOC entry 6 (class 2615 OID 16892)
-- Name: resident; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA resident;


ALTER SCHEMA resident OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 16930)
-- Name: RoleClaims; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."RoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE auth."RoleClaims" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16929)
-- Name: RoleClaims_Id_seq; Type: SEQUENCE; Schema: auth; Owner: postgres
--

ALTER TABLE auth."RoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth."RoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16902)
-- Name: Roles; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."Roles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE auth."Roles" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16943)
-- Name: UserClaims; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE auth."UserClaims" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16942)
-- Name: UserClaims_Id_seq; Type: SEQUENCE; Schema: auth; Owner: postgres
--

ALTER TABLE auth."UserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth."UserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16955)
-- Name: UserLogins; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE auth."UserLogins" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16967)
-- Name: UserRoles; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE auth."UserRoles" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16984)
-- Name: UserTokens; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE auth."UserTokens" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16909)
-- Name: Users; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."Users" (
    "Id" text NOT NULL,
    "FirstName" text NOT NULL,
    "MiddleName" text,
    "LastName" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE auth."Users" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16887)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16917)
-- Name: ResidentWeights; Type: TABLE; Schema: resident; Owner: postgres
--

CREATE TABLE resident."ResidentWeights" (
    "Id" integer NOT NULL,
    "ResidentId" integer NOT NULL,
    "DateTime" timestamp with time zone NOT NULL,
    "Weight" numeric NOT NULL
);


ALTER TABLE resident."ResidentWeights" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16916)
-- Name: ResidentWeights_Id_seq; Type: SEQUENCE; Schema: resident; Owner: postgres
--

ALTER TABLE resident."ResidentWeights" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resident."ResidentWeights_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16895)
-- Name: Residents; Type: TABLE; Schema: resident; Owner: postgres
--

CREATE TABLE resident."Residents" (
    "Id" integer NOT NULL,
    "FirstName" text,
    "MiddleName" text,
    "LastName" text,
    "Dob" date,
    "Photo" text
);


ALTER TABLE resident."Residents" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16894)
-- Name: Residents_Id_seq; Type: SEQUENCE; Schema: resident; Owner: postgres
--

ALTER TABLE resident."Residents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resident."Residents_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3679 (class 0 OID 16930)
-- Dependencies: 227
-- Data for Name: RoleClaims; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."RoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3674 (class 0 OID 16902)
-- Dependencies: 222
-- Data for Name: Roles; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- TOC entry 3681 (class 0 OID 16943)
-- Dependencies: 229
-- Data for Name: UserClaims; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3682 (class 0 OID 16955)
-- Dependencies: 230
-- Data for Name: UserLogins; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- TOC entry 3683 (class 0 OID 16967)
-- Dependencies: 231
-- Data for Name: UserRoles; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- TOC entry 3684 (class 0 OID 16984)
-- Dependencies: 232
-- Data for Name: UserTokens; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- TOC entry 3675 (class 0 OID 16909)
-- Dependencies: 223
-- Data for Name: Users; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."Users" ("Id", "FirstName", "MiddleName", "LastName", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
83e471d1-b97a-494a-a41f-88149913f91f	Prabhat	\N	Mandal	pp	PP	\N	\N	f	AQAAAAIAAYagAAAAECiL03C7VOsdYxwoQHKSfZTbq5jfF8lsKPOqfNCLnkTNVkMPwa+/ab8rFG6AS0KfFg==	J5V2VAOQX6FPLODSYEBKL35AREN5UHUC	a5b205e5-888d-4a6c-8d5e-af83ea932e86	\N	f	f	\N	t	0
8feaace5-1fcf-453a-8455-8071946eaf08	Ashwini	\N	Thapa	aa	AA	\N	\N	f	AQAAAAIAAYagAAAAEG+YEjyLsdd2Qy7IaB1U3cLa+WgaQgOgOfg7FHzAMzI71cW0sIsu+5IpR5Wcp0Ikbg==	7JVJJKOVWTORK46HAQQIEP2DTDUMXVYM	5d4b2e6b-1a19-4e81-a726-24102a454d96	\N	f	f	\N	t	0
\.


--
-- TOC entry 3671 (class 0 OID 16887)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260302085628_InitialCreate	9.0.9
\.


--
-- TOC entry 3677 (class 0 OID 16917)
-- Dependencies: 225
-- Data for Name: ResidentWeights; Type: TABLE DATA; Schema: resident; Owner: postgres
--

COPY resident."ResidentWeights" ("Id", "ResidentId", "DateTime", "Weight") FROM stdin;
1	1	2014-01-01 00:00:00+11	60
2	1	2014-01-02 00:00:00+11	65
3	1	2014-01-03 00:00:00+11	63
4	1	2014-01-04 00:00:00+11	63
5	1	2014-01-05 00:00:00+11	63.5
\.


--
-- TOC entry 3673 (class 0 OID 16895)
-- Dependencies: 221
-- Data for Name: Residents; Type: TABLE DATA; Schema: resident; Owner: postgres
--

COPY resident."Residents" ("Id", "FirstName", "MiddleName", "LastName", "Dob", "Photo") FROM stdin;
1	Jack	\N	Arthur	1990-01-01	/uploads/residents/1.jpeg
2	Helen	\N	Smith	1990-01-12	/uploads/residents/2.jpeg
5	Ash	\N	Thapa	1998-12-16	/uploads/residents/aeaad7d4-394c-4766-b3be-d346a12a0660.png
10	test	\N	test	2026-05-24	/uploads/residents/59bc32e6-a7a0-4414-a4cc-edd75cca5fc9.png
\.


--
-- TOC entry 3690 (class 0 OID 0)
-- Dependencies: 226
-- Name: RoleClaims_Id_seq; Type: SEQUENCE SET; Schema: auth; Owner: postgres
--

SELECT pg_catalog.setval('auth."RoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3691 (class 0 OID 0)
-- Dependencies: 228
-- Name: UserClaims_Id_seq; Type: SEQUENCE SET; Schema: auth; Owner: postgres
--

SELECT pg_catalog.setval('auth."UserClaims_Id_seq"', 1, false);


--
-- TOC entry 3692 (class 0 OID 0)
-- Dependencies: 224
-- Name: ResidentWeights_Id_seq; Type: SEQUENCE SET; Schema: resident; Owner: postgres
--

SELECT pg_catalog.setval('resident."ResidentWeights_Id_seq"', 5, true);


--
-- TOC entry 3693 (class 0 OID 0)
-- Dependencies: 220
-- Name: Residents_Id_seq; Type: SEQUENCE SET; Schema: resident; Owner: postgres
--

SELECT pg_catalog.setval('resident."Residents_Id_seq"', 10, true);


--
-- TOC entry 3507 (class 2606 OID 16936)
-- Name: RoleClaims PK_RoleClaims; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."RoleClaims"
    ADD CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3496 (class 2606 OID 16908)
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- TOC entry 3510 (class 2606 OID 16949)
-- Name: UserClaims PK_UserClaims; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserClaims"
    ADD CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3513 (class 2606 OID 16961)
-- Name: UserLogins PK_UserLogins; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserLogins"
    ADD CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3516 (class 2606 OID 16973)
-- Name: UserRoles PK_UserRoles; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserRoles"
    ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3518 (class 2606 OID 16990)
-- Name: UserTokens PK_UserTokens; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserTokens"
    ADD CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3500 (class 2606 OID 16915)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3492 (class 2606 OID 16891)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3504 (class 2606 OID 16923)
-- Name: ResidentWeights PK_ResidentWeights; Type: CONSTRAINT; Schema: resident; Owner: postgres
--

ALTER TABLE ONLY resident."ResidentWeights"
    ADD CONSTRAINT "PK_ResidentWeights" PRIMARY KEY ("Id");


--
-- TOC entry 3494 (class 2606 OID 16901)
-- Name: Residents PK_Residents; Type: CONSTRAINT; Schema: resident; Owner: postgres
--

ALTER TABLE ONLY resident."Residents"
    ADD CONSTRAINT "PK_Residents" PRIMARY KEY ("Id");


--
-- TOC entry 3498 (class 1259 OID 17002)
-- Name: EmailIndex; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "EmailIndex" ON auth."Users" USING btree ("NormalizedEmail");


--
-- TOC entry 3505 (class 1259 OID 16997)
-- Name: IX_RoleClaims_RoleId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_RoleClaims_RoleId" ON auth."RoleClaims" USING btree ("RoleId");


--
-- TOC entry 3508 (class 1259 OID 16999)
-- Name: IX_UserClaims_UserId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_UserClaims_UserId" ON auth."UserClaims" USING btree ("UserId");


--
-- TOC entry 3511 (class 1259 OID 17000)
-- Name: IX_UserLogins_UserId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_UserLogins_UserId" ON auth."UserLogins" USING btree ("UserId");


--
-- TOC entry 3514 (class 1259 OID 17001)
-- Name: IX_UserRoles_RoleId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_UserRoles_RoleId" ON auth."UserRoles" USING btree ("RoleId");


--
-- TOC entry 3497 (class 1259 OID 16998)
-- Name: RoleNameIndex; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON auth."Roles" USING btree ("NormalizedName");


--
-- TOC entry 3501 (class 1259 OID 17003)
-- Name: UserNameIndex; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON auth."Users" USING btree ("NormalizedUserName");


--
-- TOC entry 3502 (class 1259 OID 16996)
-- Name: IX_ResidentWeights_ResidentId; Type: INDEX; Schema: resident; Owner: postgres
--

CREATE INDEX "IX_ResidentWeights_ResidentId" ON resident."ResidentWeights" USING btree ("ResidentId");


--
-- TOC entry 3520 (class 2606 OID 16937)
-- Name: RoleClaims FK_RoleClaims_Roles_RoleId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."RoleClaims"
    ADD CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES auth."Roles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3521 (class 2606 OID 16950)
-- Name: UserClaims FK_UserClaims_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserClaims"
    ADD CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3522 (class 2606 OID 16962)
-- Name: UserLogins FK_UserLogins_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserLogins"
    ADD CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3523 (class 2606 OID 16974)
-- Name: UserRoles FK_UserRoles_Roles_RoleId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserRoles"
    ADD CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES auth."Roles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3524 (class 2606 OID 16979)
-- Name: UserRoles FK_UserRoles_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserRoles"
    ADD CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3525 (class 2606 OID 16991)
-- Name: UserTokens FK_UserTokens_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserTokens"
    ADD CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3519 (class 2606 OID 16924)
-- Name: ResidentWeights FK_ResidentWeights_Residents_ResidentId; Type: FK CONSTRAINT; Schema: resident; Owner: postgres
--

ALTER TABLE ONLY resident."ResidentWeights"
    ADD CONSTRAINT "FK_ResidentWeights_Residents_ResidentId" FOREIGN KEY ("ResidentId") REFERENCES resident."Residents"("Id") ON DELETE CASCADE;


-- Completed on 2026-05-30 09:14:18 AEST

--
-- PostgreSQL database dump complete
--

