--
-- PostgreSQL database dump
--

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg13+1)
-- Dumped by pg_dump version 17.5

-- Started on 2026-06-16 20:54:00 AEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16385)
-- Name: auth; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA auth;


ALTER SCHEMA auth OWNER TO postgres;

--
-- TOC entry 7 (class 2615 OID 16386)
-- Name: resident; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA resident;


ALTER SCHEMA resident OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16387)
-- Name: RoleClaims; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."RoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE auth."RoleClaims" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16392)
-- Name: RoleClaims_Id_seq; Type: SEQUENCE; Schema: auth; Owner: postgres
--

ALTER TABLE auth."RoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth."RoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16393)
-- Name: Roles; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."Roles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE auth."Roles" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16398)
-- Name: UserClaims; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE auth."UserClaims" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16403)
-- Name: UserClaims_Id_seq; Type: SEQUENCE; Schema: auth; Owner: postgres
--

ALTER TABLE auth."UserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth."UserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16404)
-- Name: UserLogins; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE auth."UserLogins" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16409)
-- Name: UserRoles; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE auth."UserRoles" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16414)
-- Name: UserTokens; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."UserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE auth."UserTokens" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16419)
-- Name: Users; Type: TABLE; Schema: auth; Owner: postgres
--

CREATE TABLE auth."Users" (
    "Id" text NOT NULL,
    "FirstName" text NOT NULL,
    "MiddleName" text,
    "LastName" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE auth."Users" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16424)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16427)
-- Name: ResidentWeights; Type: TABLE; Schema: resident; Owner: postgres
--

CREATE TABLE resident."ResidentWeights" (
    "Id" integer NOT NULL,
    "ResidentId" integer NOT NULL,
    "DateTime" timestamp with time zone NOT NULL,
    "Weight" numeric NOT NULL
);


ALTER TABLE resident."ResidentWeights" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16432)
-- Name: ResidentWeights_Id_seq; Type: SEQUENCE; Schema: resident; Owner: postgres
--

ALTER TABLE resident."ResidentWeights" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resident."ResidentWeights_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16433)
-- Name: Residents; Type: TABLE; Schema: resident; Owner: postgres
--

CREATE TABLE resident."Residents" (
    "Id" integer NOT NULL,
    "FirstName" text,
    "MiddleName" text,
    "LastName" text,
    "Dob" date,
    "Photo" text
);


ALTER TABLE resident."Residents" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16438)
-- Name: Residents_Id_seq; Type: SEQUENCE; Schema: resident; Owner: postgres
--

ALTER TABLE resident."Residents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME resident."Residents_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3495 (class 0 OID 16387)
-- Dependencies: 219
-- Data for Name: RoleClaims; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."RoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3497 (class 0 OID 16393)
-- Dependencies: 221
-- Data for Name: Roles; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."Roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- TOC entry 3498 (class 0 OID 16398)
-- Dependencies: 222
-- Data for Name: UserClaims; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3500 (class 0 OID 16404)
-- Dependencies: 224
-- Data for Name: UserLogins; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- TOC entry 3501 (class 0 OID 16409)
-- Dependencies: 225
-- Data for Name: UserRoles; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- TOC entry 3502 (class 0 OID 16414)
-- Dependencies: 226
-- Data for Name: UserTokens; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."UserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- TOC entry 3503 (class 0 OID 16419)
-- Dependencies: 227
-- Data for Name: Users; Type: TABLE DATA; Schema: auth; Owner: postgres
--

COPY auth."Users" ("Id", "FirstName", "MiddleName", "LastName", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
83e471d1-b97a-494a-a41f-88149913f91f	Prabhat	\N	Mandal	pp	PP	\N	\N	f	AQAAAAIAAYagAAAAECiL03C7VOsdYxwoQHKSfZTbq5jfF8lsKPOqfNCLnkTNVkMPwa+/ab8rFG6AS0KfFg==	J5V2VAOQX6FPLODSYEBKL35AREN5UHUC	a5b205e5-888d-4a6c-8d5e-af83ea932e86	\N	f	f	\N	t	0
8feaace5-1fcf-453a-8455-8071946eaf08	Ashwini	\N	Thapa	aa	AA	\N	\N	f	AQAAAAIAAYagAAAAEG+YEjyLsdd2Qy7IaB1U3cLa+WgaQgOgOfg7FHzAMzI71cW0sIsu+5IpR5Wcp0Ikbg==	7JVJJKOVWTORK46HAQQIEP2DTDUMXVYM	5d4b2e6b-1a19-4e81-a726-24102a454d96	\N	f	f	\N	t	0
\.


--
-- TOC entry 3504 (class 0 OID 16424)
-- Dependencies: 228
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260302085628_InitialCreate	9.0.9
\.


--
-- TOC entry 3505 (class 0 OID 16427)
-- Dependencies: 229
-- Data for Name: ResidentWeights; Type: TABLE DATA; Schema: resident; Owner: postgres
--

COPY resident."ResidentWeights" ("Id", "ResidentId", "DateTime", "Weight") FROM stdin;
6	11	2026-05-01 00:00:00+00	51
7	11	2026-04-01 00:00:00+00	50
8	11	2026-03-01 00:00:00+00	59
9	11	2026-02-01 00:00:00+00	57
10	11	2026-01-01 00:00:00+00	55
11	12	2026-05-01 00:00:00+00	78
12	12	2026-04-01 00:00:00+00	80
13	12	2026-03-01 00:00:00+00	79
14	12	2026-02-01 00:00:00+00	74
15	12	2026-01-01 00:00:00+00	75
17	13	2026-05-01 00:00:00+00	55
18	13	2026-04-01 00:00:00+00	60
19	13	2026-03-01 00:00:00+00	55
20	13	2026-02-01 00:00:00+00	60
21	13	2026-01-01 00:00:00+00	55
\.


--
-- TOC entry 3507 (class 0 OID 16433)
-- Dependencies: 231
-- Data for Name: Residents; Type: TABLE DATA; Schema: resident; Owner: postgres
--

COPY resident."Residents" ("Id", "FirstName", "MiddleName", "LastName", "Dob", "Photo") FROM stdin;
11	Passion	\N	Fruit	1998-01-02	/uploads/residents/2b246bde-6e0c-47b2-9b8c-cdfb57dedc18.png
12	Blueberry 	\N	Pancake	2001-06-28	/uploads/residents/7285493e-7dd7-4c4c-b5c5-02f72a77a0d8.png
13	Chilli	\N	Bomb	2003-12-10	/uploads/residents/c9bac2e4-44fd-4da2-925e-247b0c2d2c95.png
\.


--
-- TOC entry 3514 (class 0 OID 0)
-- Dependencies: 220
-- Name: RoleClaims_Id_seq; Type: SEQUENCE SET; Schema: auth; Owner: postgres
--

SELECT pg_catalog.setval('auth."RoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3515 (class 0 OID 0)
-- Dependencies: 223
-- Name: UserClaims_Id_seq; Type: SEQUENCE SET; Schema: auth; Owner: postgres
--

SELECT pg_catalog.setval('auth."UserClaims_Id_seq"', 1, false);


--
-- TOC entry 3516 (class 0 OID 0)
-- Dependencies: 230
-- Name: ResidentWeights_Id_seq; Type: SEQUENCE SET; Schema: resident; Owner: postgres
--

SELECT pg_catalog.setval('resident."ResidentWeights_Id_seq"', 21, true);


--
-- TOC entry 3517 (class 0 OID 0)
-- Dependencies: 232
-- Name: Residents_Id_seq; Type: SEQUENCE SET; Schema: resident; Owner: postgres
--

SELECT pg_catalog.setval('resident."Residents_Id_seq"', 13, true);


--
-- TOC entry 3317 (class 2606 OID 16440)
-- Name: RoleClaims PK_RoleClaims; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."RoleClaims"
    ADD CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3319 (class 2606 OID 16442)
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- TOC entry 3323 (class 2606 OID 16444)
-- Name: UserClaims PK_UserClaims; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserClaims"
    ADD CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3326 (class 2606 OID 16446)
-- Name: UserLogins PK_UserLogins; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserLogins"
    ADD CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3329 (class 2606 OID 16448)
-- Name: UserRoles PK_UserRoles; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserRoles"
    ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3331 (class 2606 OID 16450)
-- Name: UserTokens PK_UserTokens; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserTokens"
    ADD CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3334 (class 2606 OID 16452)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3337 (class 2606 OID 16454)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3340 (class 2606 OID 16456)
-- Name: ResidentWeights PK_ResidentWeights; Type: CONSTRAINT; Schema: resident; Owner: postgres
--

ALTER TABLE ONLY resident."ResidentWeights"
    ADD CONSTRAINT "PK_ResidentWeights" PRIMARY KEY ("Id");


--
-- TOC entry 3342 (class 2606 OID 16458)
-- Name: Residents PK_Residents; Type: CONSTRAINT; Schema: resident; Owner: postgres
--

ALTER TABLE ONLY resident."Residents"
    ADD CONSTRAINT "PK_Residents" PRIMARY KEY ("Id");


--
-- TOC entry 3332 (class 1259 OID 16459)
-- Name: EmailIndex; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "EmailIndex" ON auth."Users" USING btree ("NormalizedEmail");


--
-- TOC entry 3315 (class 1259 OID 16460)
-- Name: IX_RoleClaims_RoleId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_RoleClaims_RoleId" ON auth."RoleClaims" USING btree ("RoleId");


--
-- TOC entry 3321 (class 1259 OID 16461)
-- Name: IX_UserClaims_UserId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_UserClaims_UserId" ON auth."UserClaims" USING btree ("UserId");


--
-- TOC entry 3324 (class 1259 OID 16462)
-- Name: IX_UserLogins_UserId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_UserLogins_UserId" ON auth."UserLogins" USING btree ("UserId");


--
-- TOC entry 3327 (class 1259 OID 16463)
-- Name: IX_UserRoles_RoleId; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE INDEX "IX_UserRoles_RoleId" ON auth."UserRoles" USING btree ("RoleId");


--
-- TOC entry 3320 (class 1259 OID 16464)
-- Name: RoleNameIndex; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON auth."Roles" USING btree ("NormalizedName");


--
-- TOC entry 3335 (class 1259 OID 16465)
-- Name: UserNameIndex; Type: INDEX; Schema: auth; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON auth."Users" USING btree ("NormalizedUserName");


--
-- TOC entry 3338 (class 1259 OID 16466)
-- Name: IX_ResidentWeights_ResidentId; Type: INDEX; Schema: resident; Owner: postgres
--

CREATE INDEX "IX_ResidentWeights_ResidentId" ON resident."ResidentWeights" USING btree ("ResidentId");


--
-- TOC entry 3343 (class 2606 OID 16467)
-- Name: RoleClaims FK_RoleClaims_Roles_RoleId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."RoleClaims"
    ADD CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES auth."Roles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3344 (class 2606 OID 16472)
-- Name: UserClaims FK_UserClaims_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserClaims"
    ADD CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3345 (class 2606 OID 16477)
-- Name: UserLogins FK_UserLogins_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserLogins"
    ADD CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3346 (class 2606 OID 16482)
-- Name: UserRoles FK_UserRoles_Roles_RoleId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserRoles"
    ADD CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES auth."Roles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3347 (class 2606 OID 16487)
-- Name: UserRoles FK_UserRoles_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserRoles"
    ADD CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3348 (class 2606 OID 16492)
-- Name: UserTokens FK_UserTokens_Users_UserId; Type: FK CONSTRAINT; Schema: auth; Owner: postgres
--

ALTER TABLE ONLY auth."UserTokens"
    ADD CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES auth."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 3349 (class 2606 OID 16497)
-- Name: ResidentWeights FK_ResidentWeights_Residents_ResidentId; Type: FK CONSTRAINT; Schema: resident; Owner: postgres
--

ALTER TABLE ONLY resident."ResidentWeights"
    ADD CONSTRAINT "FK_ResidentWeights_Residents_ResidentId" FOREIGN KEY ("ResidentId") REFERENCES resident."Residents"("Id") ON DELETE CASCADE;


-- Completed on 2026-06-16 20:54:00 AEST

--
-- PostgreSQL database dump complete
--

